services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db
    networks:
      - network

  authentication:
    image: kireboshkovski/authentication:latest
    restart: unless-stopped
    environment:
      MONGO_URI: ${AUTH_MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
    depends_on:
      - mongo
    networks:
      - network

  backend:
    image: kireboshkovski/backend:latest
    restart: unless-stopped
    environment:
      MONGO_URI: ${BACKEND_MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - authentication
    networks:
      - network

  frontend:
    image: kireboshkovski/frontend:latest
    restart: unless-stopped
    environment:
      API_BACKEND: ${BACKEND_API_URL}
      API_AUTH: ${AUTH_API_URL}
    ports:
      - 4200:80 
    depends_on:
      - backend
      - authentication
    networks:
      - network

volumes:
  mongo-data:
    driver: local

networks:
  network:
    driver: bridge
