apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: main
data:
  MONGO_INITDB_DATABASE: "test"
  AUTH_MONGO_URI: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongo:27017/auth?authSource=admin"
  BACKEND_MONGO_URI: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongo:27017/backend?authSource=admin"
  BACKEND_API_URL: "http://backend:5000"
  AUTH_API_URL: "http://authentication:4000"
