apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kireboshkovski/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: API_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKEND_API_URL
            - name: API_AUTH
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_API_URL
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
